# type: object name
# color: RGB masking color of the object
palette:
  - type: BLACK
    color: [0, 0, 0]
  - type: ROAD
    color: [128, 128, 128]
  - type: VEGETATION
    color: [0, 255, 0]
  - type: TRAFFICISLAND
    color: [153, 51, 255]
  - type: SIDEWALK
    color: [0, 0, 255]
  - type: PARKING
    color: [255, 255, 0]
  - type: SYMBOL
    color: [255, 0, 0]
  - type: LANEMARKING
    color: [0, 128, 128]

# define the reigon you want to ignore in the mask
ignore:

# meta of GPS image
meta:
  'demo':
      origin:
          - 292161.665
          - 5630314.6051
      scale:
          - 0.05000433957147767
          - 0.050011118737163816
      proj: 'epsg:25832'
      width: 3687
      height: 1457
